//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public string MaCTHD { get; set; }
        public string MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string LoaiSan { get; set; }
        public Nullable<int> SoSan { get; set; }
        public Nullable<double> SoGioDat { get; set; }
        public Nullable<double> GiaTien { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
